import test from 'node:test'
import assert from 'node:assert/strict'
import { access, readFile } from 'node:fs/promises'

test('index shell exposes server-side UI theme placeholders without hard-coded theme assets', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8')

  assert.match(html, /<html lang="zh-CN" data-ui-theme="classic" data-terminal-visible-rows="20">/)
  assert.match(html, /data-terminal-visible-rows="20"/)
  assert.match(html, /<!-- theme-style-link -->/)
  assert.match(html, /<!-- theme-script-link -->/)
  assert.doesNotMatch(html, /terminal-theme-link/)
  assert.doesNotMatch(html, /href="\/rank-addon\/assets\/styles\.css"/)
  assert.doesNotMatch(html, /src="\/rank-addon\/assets\/app\.js"/)
})

test('server injects configured UI theme assets from per-theme folders', async () => {
  const server = await readFile(new URL('../server.mjs', import.meta.url), 'utf8')

  assert.match(server, /function renderIndexHtml/)
  assert.match(server, /function getThemeAssetTags/)
  assert.match(server, /data-ui-theme="classic"/)
  assert.match(server, /theme-style-link/)
  assert.match(server, /theme-script-link/)
  assert.match(server, /data-terminal-visible-rows="20"/)
  assert.match(server, /config\.ui\.terminal\.visibleRows/)
  assert.match(server, /\/rank-addon\/assets\/themes\/\$\{theme\}\/styles\.css/)
  assert.match(server, /\/rank-addon\/assets\/themes\/\$\{theme\}\/app\.js/)
  assert.doesNotMatch(server, /\/rank-addon\/assets\/styles\.css/)
  assert.doesNotMatch(server, /\/rank-addon\/assets\/terminal\.css/)
  assert.doesNotMatch(server, /\/rank-addon\/assets\/app\.js/)
})

test('theme-specific files live in isolated theme folders', async () => {
  await access(new URL('../public/shared/app-core.js', import.meta.url))
  await access(new URL('../public/themes/classic/styles.css', import.meta.url))
  await access(new URL('../public/themes/classic/app.js', import.meta.url))
  await access(new URL('../public/themes/terminal/styles.css', import.meta.url))
  await access(new URL('../public/themes/terminal/app.js', import.meta.url))
})

test('classic theme assets do not include terminal-only behavior', async () => {
  const app = await readFile(new URL('../public/themes/classic/app.js', import.meta.url), 'utf8')
  const css = await readFile(new URL('../public/themes/classic/styles.css', import.meta.url), 'utf8')

  assert.match(app, /startRankApp/)
  assert.match(app, /renderClassicRankChart/)
  assert.match(app, /handleInfiniteScroll/)
  assert.doesNotMatch(app, /installTerminalChrome/)
  assert.doesNotMatch(app, /renderTerminalRankChart/)
  assert.doesNotMatch(app, /Last login:/)
  assert.doesNotMatch(app, /terminal-table-row/)
  assert.doesNotMatch(css, /data-ui-theme='terminal'/)
  assert.doesNotMatch(css, /terminal-/)
})

test('terminal stylesheet is isolated, follows dark mode, and draws aligned column borders', async () => {
  const css = await readFile(new URL('../public/themes/terminal/styles.css', import.meta.url), 'utf8')

  assert.match(css, /:root\[data-ui-theme='terminal'\]/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\]/)
  assert.match(css, /\.terminal-window/)
  assert.match(css, /\.terminal-titlebar/)
  assert.match(css, /\.terminal-light\s*\{[^}]*background:\s*#ff5f57/s)
  assert.match(css, /--terminal-window-bg:\s*#fff/)
  assert.match(css, /--terminal-text:\s*#000/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\s*\{[^}]*background:\s*var\(--terminal-desktop\)/s)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\][\s\S]*--terminal-window-bg:\s*#000/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\][\s\S]*--terminal-text:\s*#fff/)
  assert.match(css, /--terminal-visible-rows:\s*20/)
  assert.match(css, /--terminal-row-height:\s*calc\(13px \* 1\.5 \+ 2px\)/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\s+body\s*\{[^}]*display:\s*flow-root/s)
  assert.match(css, /\.terminal-window\s*\{[^}]*max-height:\s*calc\(100vh - 64px\)[^}]*display:\s*flex[^}]*flex-direction:\s*column/s)
  assert.match(css, /\.panel\s*\{[^}]*flex:\s*none[^}]*min-height:\s*0/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*height:\s*calc\(var\(--terminal-row-height\) \* \(var\(--terminal-visible-rows\) \+ 1\)\)[^}]*overflow:\s*auto/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*scroll-padding-top:\s*var\(--terminal-row-height\)/s)
  assert.match(css, /\.terminal-table-row\[data-rank-index\]\s*\{[^}]*scroll-margin-top:\s*var\(--terminal-row-height\)/s)
  assert.match(css, /\.terminal-status\s*\{[^}]*height:\s*calc\(13px \* 1\.45 \* 3\)[^}]*padding:\s*0[^}]*white-space:\s*pre/s)
  assert.match(css, /\.page-head,[\s\S]*?\.toolbar,[\s\S]*?\.summary-grid,[\s\S]*?\.panel-head,[\s\S]*?\.scroll-hint\s*\{[\s\S]*?display:\s*none/s)
  assert.match(css, /\.terminal-prompt::after\s*\{[\s\S]*?content:\s*''/s)
  assert.match(css, /\.terminal-table-row\s*\{[^}]*display:\s*grid/s)
  assert.match(css, /\.terminal-table-head\s*\{[^}]*position:\s*sticky[^}]*top:\s*0/s)
  assert.doesNotMatch(css, /\.terminal-table-row\.is-current/)
  assert.match(css, /\.terminal-star\s*\{[^}]*font-size:\s*1\.2em[^}]*line-height:\s*0/s)
  assert.match(css, /\.terminal-table-row\.is-selected\s*\{[\s\S]*?background:\s*var\(--terminal-selected-bg\)[\s\S]*?color:\s*var\(--terminal-selected-text\)/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*scrollbar-width:\s*none/s)
  assert.match(css, /\.rank-chart\.terminal-output::-webkit-scrollbar\s*\{[^}]*display:\s*none/s)
  assert.doesNotMatch(css, /;\n\s*height:\s*100vh/)
  assert.doesNotMatch(css, /\.terminal-table-row\s*>\s*\*\s*\+\s*\*\s*\{[^}]*border-left:/s)
  assert.doesNotMatch(css, /content:\s*['"`][│|]/)
  assert.doesNotMatch(css, /\.rank-row/)
  assert.doesNotMatch(css, /\.bar-track/)
  assert.doesNotMatch(css, /\.tier-bronze/)
})

test('terminal theme app renders terminal rows and keyboard controls without classic branching', async () => {
  const app = await readFile(new URL('../public/themes/terminal/app.js', import.meta.url), 'utf8')

  assert.match(app, /startRankApp/)
  assert.match(app, /installKeyboardControls\(\)/)
  assert.match(app, /function renderTerminalRankChart/)
  assert.match(app, /Last login:/)
  assert.match(app, /function formatTerminalLoginTime/)
  assert.match(app, /on ttys000/)
  assert.match(app, /const TERMINAL_DEFAULT_VISIBLE_ROWS = 20/)
  assert.match(app, /function getTerminalVisibleRows/)
  assert.match(app, /function resetTerminalRankScroll/)
  assert.match(app, /resetTerminalRankScroll\(\)/)
  assert.match(app, /--terminal-visible-rows/)
  assert.match(app, /document\.querySelector\('\.panel'\)/)
  assert.match(app, /panel\?\.after\(status\)/)
  assert.match(app, /function formatTerminalTier/)
  assert.match(app, /getTerminalStarSymbol/)
  assert.match(app, /['"]★['"]/)
  assert.match(app, /['"]☆['"]/)
  assert.match(app, /formatTerminalTier[\s\S]*replaceAll\('⭐️', getTerminalStarSymbol\(\)\)[\s\S]*replaceAll\('⭐', getTerminalStarSymbol\(\)\)/)
  assert.doesNotMatch(app, /function formatTerminalRankChart[\s\S]*formatTier\(row\.tier \|\| \{\}\)/)
  assert.doesNotMatch(app, /Last login: today/)
  assert.doesNotMatch(app, /refresh=running/)
  assert.match(app, /const visibleRows = rows/)
  assert.match(app, /keys: 1 day 2 week 3 month 4 all, j\/k move, r refresh/)
  assert.match(app, /terminal-table-row/)
  assert.match(app, /terminal-star/)
  assert.doesNotMatch(app, /item\.classList\.toggle\('is-current'/)
  assert.match(app, /aria-selected/)
  assert.match(app, /is-selected/)
  assert.match(app, /function isEditableTarget/)
  assert.doesNotMatch(app, /target instanceof HTMLElement/)
  assert.match(app, /tagName === 'INPUT'/)
  assert.match(app, /tagName === 'TEXTAREA'/)
  assert.match(app, /isContentEditable/)
  assert.match(app, /function installParentKeyboardBridge/)
  assert.match(app, /function getSameOriginParentWindow/)
  assert.match(app, /window\.parent !== window/)
  assert.match(app, /window\.parent\.location\.origin/)
  assert.match(app, /parentWindow\.addEventListener\('keydown'/)
  assert.match(app, /parentWindow\.removeEventListener\('keydown'/)
  assert.match(app, /window\.addEventListener\(\s*'pagehide'/)
  assert.match(app, /window\.addEventListener\(\s*'pageshow'/)
  assert.match(app, /event\.persisted/)
  assert.match(app, /function addParentKeyboardListener/)
  assert.match(app, /function removeParentKeyboardListener/)
  assert.match(app, /function handleTerminalShortcut/)
  assert.match(app, /case '1':/)
  assert.match(app, /selectPeriod\('day'\)/)
  assert.match(app, /case '2':/)
  assert.match(app, /selectPeriod\('week'\)/)
  assert.match(app, /case '3':/)
  assert.match(app, /selectPeriod\('month'\)/)
  assert.match(app, /case '4':/)
  assert.match(app, /selectPeriod\('all'\)/)
  assert.match(app, /case 'j':/)
  assert.match(app, /case 'ArrowDown':/)
  assert.match(app, /case 'k':/)
  assert.match(app, /case 'ArrowUp':/)
  assert.match(app, /case 'r':/)
  assert.doesNotMatch(app, /[│┆┊]\s*\$\{/)
  assert.doesNotMatch(app, /isTerminalTheme/)
  assert.doesNotMatch(app, /renderClassicRankChart/)
})

test('example config and README document config-file theme switching', async () => {
  const example = await readFile(new URL('../config.example.json', import.meta.url), 'utf8')
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8')

  assert.match(example, /"ui"\s*:\s*\{[\s\S]*"theme"\s*:\s*"classic"/)
  assert.match(example, /"terminal"\s*:\s*\{[\s\S]*"visibleRows"\s*:\s*20/)
  assert.match(readme, /`ui\.theme`/)
  assert.match(readme, /`ui\.terminal\.visibleRows`/)
  assert.match(readme, /macOS Terminal\.app/)
  assert.match(readme, /固定窗口尺寸/)
  assert.match(readme, /internal ranking scroll/)
  assert.match(readme, /`1`\/`2`\/`3`\/`4`/)
  assert.match(readme, /`j`\/`k`/)
  assert.match(readme, /`r`/)
  assert.match(readme, /`★` \/ `☆`/)
  assert.match(readme, /`classic`/)
  assert.match(readme, /`terminal`/)
  assert.match(readme, /config\.json/)
  assert.match(readme, /`public\/themes\/classic\/`/)
  assert.match(readme, /`public\/themes\/terminal\/`/)
  assert.match(readme, /`styles\.css`/)
  assert.match(readme, /`app\.js`/)
  assert.match(readme, /iframe/)
  assert.match(readme, /同源/)
  assert.match(readme, /父页面/)
  assert.match(readme, /无需先点击 iframe/)
  assert.doesNotMatch(readme, /主题切换按钮/)
})
