import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('index shell exposes server-side UI theme placeholders while keeping static classic fallback', async () => {
  const html = await readFile(new URL('../public/index.html', import.meta.url), 'utf8')

  assert.match(html, /<html lang="zh-CN" data-ui-theme="classic" data-terminal-visible-rows="20">/)
  assert.match(html, /data-terminal-visible-rows="20"/)
  assert.match(html, /<!-- terminal-theme-link -->/)
  assert.match(html, /href="\/rank-addon\/assets\/styles\.css"/)
})

test('server injects configured UI theme and terminal stylesheet only for terminal theme', async () => {
  const server = await readFile(new URL('../server.mjs', import.meta.url), 'utf8')

  assert.match(server, /function renderIndexHtml/)
  assert.match(server, /data-ui-theme="classic"/)
  assert.match(server, /terminal-theme-link/)
  assert.match(server, /config\.ui\.theme === 'terminal'/)
  assert.match(server, /data-terminal-visible-rows="20"/)
  assert.match(server, /config\.ui\.terminal\.visibleRows/)
  assert.match(server, /href="\/rank-addon\/assets\/terminal\.css"/)
})

test('terminal stylesheet is isolated, follows dark mode, and draws aligned column borders', async () => {
  const css = await readFile(new URL('../public/terminal.css', import.meta.url), 'utf8')

  assert.match(css, /:root\[data-ui-theme='terminal'\]/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\]/)
  assert.match(css, /\.terminal-window/)
  assert.match(css, /\.terminal-titlebar/)
  assert.match(css, /\.terminal-light\s*\{[^}]*background:\s*#ff5f57/s)
  assert.match(css, /--terminal-window-bg:\s*#fff/)
  assert.match(css, /--terminal-text:\s*#000/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\s*\{[^}]*background:\s*var\(--terminal-desktop\)/s)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\][\s\S]*--terminal-window-bg:\s*#000/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\[data-theme='dark'\][\s\S]*--terminal-text:\s*#fff/)
  assert.match(css, /--terminal-visible-rows:\s*20/)
  assert.match(css, /--terminal-row-height:\s*calc\(13px \* 1\.5 \+ 2px\)/)
  assert.match(css, /:root\[data-ui-theme='terminal'\]\s+body\s*\{[^}]*display:\s*flow-root/s)
  assert.match(css, /\.terminal-window\s*\{[^}]*max-height:\s*calc\(100vh - 64px\)[^}]*display:\s*flex[^}]*flex-direction:\s*column/s)
  assert.match(css, /\.panel\s*\{[^}]*flex:\s*none[^}]*min-height:\s*0/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*height:\s*calc\(var\(--terminal-row-height\) \* \(var\(--terminal-visible-rows\) \+ 1\)\)[^}]*overflow:\s*auto/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*scroll-padding-top:\s*var\(--terminal-row-height\)/s)
  assert.match(css, /\.terminal-table-row\[data-rank-index\]\s*\{[^}]*scroll-margin-top:\s*var\(--terminal-row-height\)/s)
  assert.match(css, /\.terminal-status\s*\{[^}]*height:\s*calc\(13px \* 1\.45 \* 3\)[^}]*padding:\s*0[^}]*white-space:\s*pre/s)
  assert.match(css, /\.page-head,[\s\S]*?\.toolbar,[\s\S]*?\.summary-grid,[\s\S]*?\.panel-head,[\s\S]*?\.scroll-hint\s*\{[\s\S]*?display:\s*none/s)
  assert.match(css, /\.terminal-prompt::after\s*\{[\s\S]*?content:\s*''/s)
  assert.match(css, /\.terminal-table-row\s*\{[^}]*display:\s*grid/s)
  assert.match(css, /\.terminal-table-head\s*\{[^}]*position:\s*sticky[^}]*top:\s*0/s)
  assert.doesNotMatch(css, /\.terminal-table-row\.is-current/)
  assert.match(css, /\.terminal-star\s*\{[^}]*font-size:\s*1\.2em[^}]*line-height:\s*0/s)
  assert.match(css, /\.terminal-table-row\.is-selected\s*\{[\s\S]*?background:\s*var\(--terminal-selected-bg\)[\s\S]*?color:\s*var\(--terminal-selected-text\)/s)
  assert.match(css, /\.rank-chart\.terminal-output\s*\{[^}]*scrollbar-width:\s*none/s)
  assert.match(css, /\.rank-chart\.terminal-output::-webkit-scrollbar\s*\{[^}]*display:\s*none/s)
  assert.doesNotMatch(css, /;\n\s*height:\s*100vh/)
  assert.doesNotMatch(css, /\.terminal-table-row\s*>\s*\*\s*\+\s*\*\s*\{[^}]*border-left:/s)
  assert.doesNotMatch(css, /content:\s*['"`][│|]/)
})

test('terminal app branch renders terminal rows and keyboard controls without editable interception', async () => {
  const app = await readFile(new URL('../public/app.js', import.meta.url), 'utf8')

  assert.match(app, /const isTerminalTheme = document\.documentElement\.dataset\.uiTheme === 'terminal'/)
  assert.match(app, /installKeyboardControls\(\)/)
  assert.match(app, /function renderTerminalRankChart/)
  assert.match(app, /Last login:/)
  assert.match(app, /function formatTerminalLoginTime/)
  assert.match(app, /on ttys000/)
  assert.match(app, /const TERMINAL_DEFAULT_VISIBLE_ROWS = 20/)
  assert.match(app, /function getTerminalVisibleRows/)
  assert.match(app, /function resetTerminalRankScroll/)
  assert.match(app, /resetTerminalRankScroll\(\)/)
  assert.match(app, /--terminal-visible-rows/)
  assert.match(app, /document\.querySelector\('\.panel'\)/)
  assert.match(app, /panel\?\.after\(status\)/)
  assert.match(app, /function formatTerminalTier/)
  assert.match(app, /getTerminalStarSymbol/)
  assert.match(app, /['"]★['"]/)
  assert.match(app, /['"]☆['"]/)
  assert.match(app, /formatTerminalTier[\s\S]*replaceAll\('⭐️', getTerminalStarSymbol\(\)\)[\s\S]*replaceAll\('⭐', getTerminalStarSymbol\(\)\)/)
  assert.doesNotMatch(app, /function formatTerminalRankChart[\s\S]*formatTier\(row\.tier \|\| \{\}\)/)
  assert.doesNotMatch(app, /Last login: today/)
  assert.doesNotMatch(app, /refresh=running/)
  assert.match(app, /const visibleRows = rows/)
  assert.match(app, /keys: 1 day 2 week 3 month 4 all, j\/k move, r refresh/)
  assert.match(app, /terminal-table-row/)
  assert.match(app, /terminal-star/)
  assert.doesNotMatch(app, /item\.classList\.toggle\('is-current'/)
  assert.match(app, /aria-selected/)
  assert.match(app, /is-selected/)
  assert.match(app, /function isEditableTarget/)
  assert.match(app, /tagName === 'INPUT'/)
  assert.match(app, /tagName === 'TEXTAREA'/)
  assert.match(app, /isContentEditable/)
  assert.match(app, /case '1':/)
  assert.match(app, /selectPeriod\('day'\)/)
  assert.match(app, /case '2':/)
  assert.match(app, /selectPeriod\('week'\)/)
  assert.match(app, /case '3':/)
  assert.match(app, /selectPeriod\('month'\)/)
  assert.match(app, /case '4':/)
  assert.match(app, /selectPeriod\('all'\)/)
  assert.match(app, /case 'j':/)
  assert.match(app, /case 'ArrowDown':/)
  assert.match(app, /case 'k':/)
  assert.match(app, /case 'ArrowUp':/)
  assert.match(app, /case 'r':/)
  assert.doesNotMatch(app, /[│┆┊]\s*\$\{/)
})

test('example config and README document config-file theme switching', async () => {
  const example = await readFile(new URL('../config.example.json', import.meta.url), 'utf8')
  const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8')

  assert.match(example, /"ui"\s*:\s*\{[\s\S]*"theme"\s*:\s*"classic"/)
  assert.match(example, /"terminal"\s*:\s*\{[\s\S]*"visibleRows"\s*:\s*20/)
  assert.match(readme, /`ui\.theme`/)
  assert.match(readme, /`ui\.terminal\.visibleRows`/)
  assert.match(readme, /`classic`/)
  assert.match(readme, /`terminal`/)
  assert.match(readme, /config\.json/)
  assert.doesNotMatch(readme, /主题切换按钮/)
})
